#eureka:
  #client:
    #serviceUrl:
      #defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: eureka-amqp
    
  rabbitmq:
    host: localhost
    virtual-host: /mq_test
    port: 5672
    username: mqtest
    password: mqtest

server:
  port: 8089
  
