server:
  port: 9002

spring:
  application:
    name: eureka-zuul-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

zuul: 
  routes: 
    blog: 
      path: /** 
 #     url: http://www.baidu.com
      serviceId: eureka-provider
  
      