spring:
  application:
    name: config-client
  cloud:
    config:
      label: master
      uri: http://localhost:8888
      profile: dev
      name: config
      
  rabbitmq:
    host: localhost
    port: 5672
    username: mqtest
    password: mqtest
    virtual-host: /mq_test
          
server:
  port: 8889

#关闭刷新安全认证
#值是false的话，除开health接口还依赖endpoints.health.sensitive的配置外，其他接口都不需要输入用户名和密码了  
management:
  security:
    enabled: false
